# Конфигурация для Accounts Service
# Файл: accounts-service.yml
# 
# Config Server будет отдавать эту конфигурацию
# когда accounts-service запросит свои настройки
#
# URL: http://localhost:8888/accounts-service/default

server:
  port: 0
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mybank?currentSchema=accounts}
    username: ${DB_USER:mybank}
    password: ${DB_PASSWORD:mybank_password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: accounts
    liquibase-schema: public
  security:
    oauth2:
      client:
        registration:
          accounts-service:
            client-id: accounts-service
            client-secret: Ycm7AwLxKchJ76kaRwDaG0RyHsp1T2rK
            authorization-grant-type: client_credentials
            scope: profile
        provider:
          accounts-service:
            token-uri: http://localhost:8080/realms/mybank/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mybank
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: accounts

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Логирование
logging:
  level:
    com.mybank.accounts: DEBUG



