spring:
  application:
    name: front-ui
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}"
logging:
  level:
    com.mybank.frontend: ERROR
