spring:
  application:
    name: front-ui
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:http://localhost:8888"
logging:
  level:
    com.mybank.frontend: ERROR
